const data=[
    { name: "GRINNING FACE", unicode: String.fromCodePoint(128512) },
    { name: "GRINNING FACE WITH SMILING EYES", unicode: String.fromCodePoint(128513) },
    { name: "FACE WITH TEARS OF JOY", unicode: String.fromCodePoint(128514) },
    { name: "WHITE SMILING FACE", unicode: String.fromCodePoint(9786) },
    { name: "SLIGHTLY SMILING FACE", unicode: String.fromCodePoint(128578) },
    { name: "HUGGING FACE", unicode: String.fromCodePoint(129303) },
    { name: "THINKING FACE", unicode: String.fromCodePoint(129300) },
    { name: "NEUTRAL FACE", unicode: String.fromCodePoint(128528) },
    { name: "EXPRESSIONLESS FACE", unicode: String.fromCodePoint(128529) },
    { name: "FACE WITHOUT MOUTH", unicode: String.fromCodePoint(128566) },
    { name: "FACE WITH ROLLING EYES", unicode: String.fromCodePoint(128580) },
    { name: "SMIRKING FACE", unicode: String.fromCodePoint(128527) },
    { name: "PERSEVERING FACE", unicode: String.fromCodePoint(128547) },
    { name: "DISAPPOINTED BUT RELIEVED FACE", unicode: String.fromCodePoint(128549) },
    { name: "FACE WITH OPEN MOUTH", unicode: String.fromCodePoint(128558) },
    { name: "ZIPPER-MOUTH FACE", unicode: String.fromCodePoint(129296) },
    { name: "HUSHED FACE", unicode: String.fromCodePoint(128559) },
    { name: "SLEEPY FACE", unicode: String.fromCodePoint(128554) },
    { name: "TIRED FACE", unicode: String.fromCodePoint(128555) },
    { name: "SLEEPING FACE", unicode: String.fromCodePoint(128564) },
    { name: "RELIEVED FACE", unicode: String.fromCodePoint(128524) },
    { name: "NERD FACE", unicode: String.fromCodePoint(129299) },
    { name: "FACE WITH STUCK-OUT TONGUE", unicode: String.fromCodePoint(128539) },
    { name: "FACE WITH STUCK-OUT TONGUE AND WINKING EYE", unicode: String.fromCodePoint(128540) },
    { name: "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES", unicode: String.fromCodePoint(128541) },
    { name: "DROOLING FACE", unicode: String.fromCodePoint(129316) },
    { name: "UNAMUSED FACE", unicode: String.fromCodePoint(128530) },
    { name: "FACE WITH COLD SWEAT", unicode: String.fromCodePoint(128531) },
    { name: "PENSIVE FACE", unicode: String.fromCodePoint(128532) },
    { name: "CONFUSED FACE", unicode: String.fromCodePoint(128533) },
    { name: "UPSIDE-DOWN FACE", unicode: String.fromCodePoint(128579) },
    { name: "MONEY-MOUTH FACE", unicode: String.fromCodePoint(129297) },
    { name: "ASTONISHED FACE", unicode: String.fromCodePoint(128562) },
    { name: "WHITE FROWNING FACE", unicode: String.fromCodePoint(9785) },
    { name: "SLIGHTLY FROWNING FACE", unicode: String.fromCodePoint(128577) },
    { name: "CONFOUNDED FACE", unicode: String.fromCodePoint(128534) },
    { name: "DISAPPOINTED FACE", unicode: String.fromCodePoint(128542) },
    { name: "WORRIED FACE", unicode: String.fromCodePoint(128543) },
    { name: "FACE WITH LOOK OF TRIUMPH", unicode: String.fromCodePoint(128548) },
    { name: "CRYING FACE", unicode: String.fromCodePoint(128546) },
    { name: "LOUDLY CRYING FACE", unicode: String.fromCodePoint(128557) },
    { name: "FROWNING FACE WITH OPEN MOUTH", unicode: String.fromCodePoint(128550) },
    { name: "ANGUISHED FACE", unicode: String.fromCodePoint(128551) },
    { name: "FEARFUL FACE", unicode: String.fromCodePoint(128552) },
    { name: "WEARY FACE", unicode: String.fromCodePoint(128553) },
    { name: "GRIMACING FACE", unicode: String.fromCodePoint(128556) },
    { name: "FACE WITH OPEN MOUTH AND COLD SWEAT", unicode: String.fromCodePoint(128560) },
    { name: "FACE SCREAMING IN FEAR", unicode: String.fromCodePoint(128561) },
    { name: "FLUSHED FACE", unicode: String.fromCodePoint(128563) },
    { name: "DIZZY FACE", unicode: String.fromCodePoint(128565) },
    { name: "POUTING FACE", unicode: String.fromCodePoint(128545) },
    { name: "ANGRY FACE", unicode: String.fromCodePoint(128544) },
    { name: "SMILING FACE WITH HALO", unicode: String.fromCodePoint(128519) },
    { name: "FACE WITH COWBOY HAT", unicode: String.fromCodePoint(129312) },
    { name: "CLOWN FACE", unicode: String.fromCodePoint(129313) },
    { name: "LYING FACE", unicode: String.fromCodePoint(129317) },
    { name: "FACE WITH MEDICAL MASK", unicode: String.fromCodePoint(128567) },
    { name: "FACE WITH THERMOMETER", unicode: String.fromCodePoint(129298) },
    { name: "FACE WITH HEAD-BANDAGE", unicode: String.fromCodePoint(129301) },
    { name: "NAUSEATED FACE", unicode: String.fromCodePoint(129314) },
    { name: "SNEEZING FACE", unicode: String.fromCodePoint(129319) },
    { name: "SMILING FACE WITH HORNS", unicode: String.fromCodePoint(128520) },
    { name: "IMP", unicode: String.fromCodePoint(128127) },
    { name: "JAPANESE OGRE", unicode: String.fromCodePoint(128121) },
    { name: "JAPANESE GOBLIN", unicode: String.fromCodePoint(128122) },
    { name: "SKULL", unicode: String.fromCodePoint(128128) },
    { name: "SKULL AND CROSSBONES", unicode: String.fromCodePoint(9760) },
    { name: "GHOST", unicode: String.fromCodePoint(128123) },
    { name: "EXTRATERRESTRIAL ALIEN", unicode: String.fromCodePoint(128125) },
    { name: "ALIEN MONSTER", unicode: String.fromCodePoint(128126) },
    { name: "ROBOT FACE", unicode: String.fromCodePoint(129302) },
    { name: "PILE OF POO", unicode: String.fromCodePoint(128169) },
    { name: "SMILING CAT FACE WITH OPEN MOUTH", unicode: String.fromCodePoint(128570) },
    { name: "GRINNING CAT FACE WITH SMILING EYES", unicode: String.fromCodePoint(128568) },
    { name: "CAT FACE WITH TEARS OF JOY", unicode: String.fromCodePoint(128569) },
    { name: "SMILING CAT FACE WITH HEART-SHAPED EYES", unicode: String.fromCodePoint(128571) },
    { name: "CAT FACE WITH WRY SMILE", unicode: String.fromCodePoint(128572) },
    { name: "KISSING CAT FACE WITH CLOSED EYES", unicode: String.fromCodePoint(128573) },
    { name: "WEARY CAT FACE", unicode: String.fromCodePoint(128576) },
    { name: "CRYING CAT FACE", unicode: String.fromCodePoint(128575) },
    { name: "POUTING CAT FACE", unicode: String.fromCodePoint(128574) },
    { name: "SEE-NO-EVIL MONKEY", unicode: String.fromCodePoint(128584) },
    { name: "HEAR-NO-EVIL MONKEY", unicode: String.fromCodePoint(128585) },
    { name: "SPEAK-NO-EVIL MONKEY", unicode: String.fromCodePoint(128586) }
    ]
  export default data;
  